//
//  SettingsModel.swift
//  iOS-Settings with MVC
//
//  Created by Анастасия on 19.08.2021.
//

import Foundation
import UIKit

final class SettingsModel {

    let configureCell = [
            "Section0": [ItemsSettings(type: .switchCell,
                               title: "Авиарежим",
                               icon: UIImage(systemName: "airplane"),
                               iconBackgroundColor: .systemOrange,
                               isOn: false),
                         ItemsSettings(type: .label,
                               title: "Wi-Fi",
                               icon: UIImage(systemName: "wifi"),
                               iconBackgroundColor: UIColor.systemBlue,
                               label: "Не подключено"),
                         ItemsSettings(type: .label,
                               title: "Bluetooth",
                               icon: UIImage(named: "bluetooth"),
                               iconBackgroundColor: .systemBlue,
                               label: "Вкл."),
                         ItemsSettings(type: .standard,
                               title: "Сотовая связь",
                               icon: UIImage(systemName: "antenna.radiowaves.left.and.right"),
                               iconBackgroundColor: .systemGreen),
                         ItemsSettings(type: .label,
                               title: "Режим модема",
                               icon: UIImage(systemName: "personalhotspot"),
                               iconBackgroundColor: .systemGreen,
                               label: "Выкл."),
                         ItemsSettings(type: .switchCell,
                               title: "VPN",
                               icon: UIImage(systemName: "globe"),
                               iconBackgroundColor: .systemBlue,
                               isOn: true)],
            "Section1": [ItemsSettings(type: .standard,
                               title: "Уведомления",
                               icon: UIImage(systemName: "note"),
                               iconBackgroundColor: .systemRed),
                         ItemsSettings(type: .standard,
                               title: "Звук, тактильные сигналы",
                               icon: UIImage(systemName: "speaker.wave.3.fill"),
                               iconBackgroundColor: .systemPink),
                         ItemsSettings(type: .standard,
                               title: "Не беспокоить",
                               icon: UIImage(systemName: "moon.fill"),
                               iconBackgroundColor: .systemIndigo),
                         ItemsSettings(type: .standard,
                               title: "Экранное время",
                               icon: UIImage(systemName: "hourglass"),
                               iconBackgroundColor: .systemIndigo)],
            "Section2": [ItemsSettings(type: .standard,
                               title: "Основные",
                               icon: UIImage(systemName: "gear"),
                               iconBackgroundColor: .systemGray),
                         ItemsSettings(type: .standard,
                               title: "Пункт управления",
                               icon: UIImage(systemName: "slider.horizontal.3"),
                               iconBackgroundColor: .systemBlue),
                         ItemsSettings(type: .standard,
                               title: "Экран и яркость",
                               icon: UIImage(systemName: "textformat.size"),
                               iconBackgroundColor: .systemBlue),
                         ItemsSettings(type: .standard,
                               title: "Экран «‎Домой»‎",
                               icon: UIImage(systemName: "apps.iphone"),
                               iconBackgroundColor: .systemIndigo),
                         ItemsSettings(type: .standard,
                               title: "Универсальный доступ",
                               icon: UIImage(systemName: "figure.stand"),
                               iconBackgroundColor: .systemBlue),
                         ItemsSettings(type: .standard,
                               title: "Обои",
                               icon: UIImage(systemName: "seal"),
                               iconBackgroundColor: .systemTeal),
                         ItemsSettings(type: .standard,
                               title: "Face ID и код-пароль",
                               icon: UIImage(systemName: "person.fill.viewfinder"),
                               iconBackgroundColor: .systemGreen),
                         ItemsSettings(type: .standard,
                               title: "Аккумулятор",
                               icon: UIImage(systemName: "battery.100"),
                               iconBackgroundColor: .systemGreen),
                         ItemsSettings(type: .standard,
                               title: "Конфиденциальность",
                               icon: UIImage(systemName: "hand.raised.fill"),
                               iconBackgroundColor: .systemBlue)]]
}
